{% set name = "autoray" %}
{% set version = "0.2.5" %}
{% set sha256 = "1c5bf914553f1d3d7d4af254f70d37b59aa20b2f6c0aa110f5b7f336c2cafbba" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy
    - python >=3.5

test:
  imports:
    - autoray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jcmgray/autoray/
  summary: Write backend agnostic numeric code compatible with any numpy-ish array library.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - jcmgray
